"""Add username

Revision ID: 17912d7fd666
Revises: 2017f96d954c
Create Date: 2026-07-05 10:09:36.687255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.util.usernames import generate_single_username

# revision identifiers, used by Alembic.
revision: str = '17912d7fd666'
down_revision: Union[str, Sequence[str], None] = '2017f96d954c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_diagnostics_name'), 'diagnostics', ['name'], unique=True)
    op.add_column('users', sa.Column('preferred_username', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

    connection = op.get_bind()

    # Reflect the current users table structure to query it safely
    meta = sa.MetaData()
    users_table = sa.Table(
        'users',
        meta,
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('preferred_username', sa.String(length=50))
    )

    # Fetch only the IDs of existing users
    users = connection.execute(sa.select(users_table.c.id)).fetchall()

    # Iterate and update rows one by one with a freshly generated name
    used_names = set()
    for user in users:
        username = generate_single_username()

        # Enforce uniqueness within this specific migration batch
        while username in used_names:
            username = generate_single_username()
        used_names.add(username)

        # Execute raw SQL update bind for efficiency
        connection.execute(
            users_table.update()
            .where(users_table.c.id == user.id)
            .values(preferred_username=username)
        )

    # 3. Enforce Constraints: Alter the column to nullable=False now that data is populated
    op.alter_column('users', 'preferred_username', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_username')
    op.drop_index(op.f('ix_diagnostics_name'), table_name='diagnostics')
    # ### end Alembic commands ###
