"""add feedback markers

Revision ID: 544f139ee69d
Revises: 2017f96d954c
Create Date: 2026-06-28 11:38:53.346197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '544f139ee69d'
down_revision: Union[str, Sequence[str], None] = '2017f96d954c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('diagnostics_name_key'), 'diagnostics', type_='unique')
    op.create_index(op.f('ix_diagnostics_name'), 'diagnostics', ['name'], unique=True)
    feedbackmarkertype = postgresql.ENUM('NONE', 'READ', 'IMPORTANT', 'LOOK_AGAIN', name='feedbackmarkertype')
    feedbackmarkertype.create(op.get_bind(), checkfirst=True)
    op.add_column('session_user_feedback', sa.Column('marker', sa.Enum('NONE', 'READ', 'IMPORTANT', 'LOOK_AGAIN', name='feedbackmarkertype'), server_default='NONE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_user_feedback', 'marker')
    op.drop_index(op.f('ix_diagnostics_name'), table_name='diagnostics')
    op.create_unique_constraint(op.f('diagnostics_name_key'), 'diagnostics', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
