"""Add audio flag

Revision ID: 55a378de9b62
Revises: 9b41861c300c
Create Date: 2026-05-07 13:02:22.388583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a378de9b62'
down_revision: Union[str, Sequence[str], None] = '9b41861c300c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('audio_transcript', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'audio_transcript')
    # ### end Alembic commands ###
