"""Add session time remaining

Revision ID: 8a1ced8bca69
Revises: 55a378de9b62
Create Date: 2026-05-09 11:38:59.230234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1ced8bca69'
down_revision: Union[str, Sequence[str], None] = '55a378de9b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('live_time_remaining', sa.Integer(), nullable=False, server_default=sa.text('600')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'live_time_remaining')
    # ### end Alembic commands ###
