"""Added live_handle

Revision ID: 9b41861c300c
Revises: c7d3e4f5a6b7
Create Date: 2026-04-27 19:23:23.684532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b41861c300c'
down_revision: Union[str, Sequence[str], None] = 'c7d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('live_api_handle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'live_api_handle')
    # ### end Alembic commands ###
