"""Add diagnostics to database

Revision ID: bc93dd2f16e3
Revises: c40836c283d5
Create Date: 2026-05-13 17:22:17.491872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc93dd2f16e3'
down_revision: Union[str, Sequence[str], None] = 'c40836c283d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_diagnostics',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('diagnostic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'diagnostic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_diagnostics')
    op.drop_table('diagnostics')
    # ### end Alembic commands ###
