"""Add student diagnosis

Revision ID: c40836c283d5
Revises: 8a1ced8bca69
Create Date: 2026-05-10 19:09:43.259170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40836c283d5'
down_revision: Union[str, Sequence[str], None] = '8a1ced8bca69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('student_diagnosis', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'student_diagnosis')
    # ### end Alembic commands ###
