name: create_release.yml

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Pre-release Status
        id: check_tag
        run: |
          # If the tag contains a hyphen (e.g., v1.2.1-beta.3), flag as pre-release
          if [[ "${{ github.ref_name }}" == *"-"* ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          prerelease: ${{ steps.check_tag.outputs.prerelease }}
          generate_release_notes: true